# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# app.py  (puedes renombrarlo a app_bim_dashboard.py si quieres)
from __future__ import annotations
import os
from datetime import datetime, timedelta
from typing import Dict, Any

import pandas as pd
import streamlit as st
from sqlalchemy import create_engine, text

# Debe ser el primer comando de Streamlit
st.set_page_config(page_title="Dashboard SQL: Make + Forms", page_icon="📊", layout="wide")

# ----------------------------
# Conexión a MySQL
# ----------------------------
def get_mysql_engine():
    if "mysql" in st.secrets:
        cfg = st.secrets["mysql"]
        host = cfg.get("host", "localhost")
        port = int(cfg.get("port", 3306))
        user = cfg.get("user")
        password = cfg.get("password")
        db = cfg.get("db")
    else:
        host = os.getenv("MYSQL_HOST", "localhost")
        port = int(os.getenv("MYSQL_PORT", "3306"))
        user = os.getenv("MYSQL_USER", "root")
        password = os.getenv("MYSQL_PASSWORD", "")
        db = os.getenv("MYSQL_DB", "technolab")
    uri = f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}?charset=utf8mb4"
    return create_engine(uri, pool_pre_ping=True, pool_recycle=1800)

# ----------------------------
# Mapeo de tablas/columnas (ajusta a tu esquema real)
# ----------------------------
CONFIG_SCHEMA: Dict[str, Dict[str, str]] = {
    "clientes": {
        "table": "clientes",
        "id": "id",
        "nombre": "cliente",
        "telefono": "telefono",
        "direccion": "direccion",
        "creado": ""
    },
    "formularios": {
        "table": "formularios",
        "id": "id",
        "cliente_id": "cliente_id",
        "tipo": "tipo_form",
        "fecha": "fecha",
        "payload": "payload"
    },
    "diagnosticos": {
        "table": "diagnosticos",
        "id": "id",
        "cliente_id": "cliente_id",
        "fecha": "fecha",
        "texto": "diagnostico",
        "usuario_id": "usuario_id"
    },
    "comentarios": {
        "table": "comentarios",
        "id": "id",
        "cliente_id": "cliente_id",
        "fecha": "fecha",
        "texto": "comentario",
        "usuario_id": "usuario_id"
    },
    "registros": {
        "table": "registros",
        "id": "id",
        "cliente_id": "cliente_id",
        "fecha": "fecha",
        "estado": "estado",
        "valor": "valor"
    }
}

# ----------------------------
# Helpers de consulta
# ----------------------------
@st.cache_data(ttl=300)
def df_clientes() -> pd.DataFrame:
    cfg = CONFIG_SCHEMA["clientes"]
    tbl = cfg["table"]
    cols = [c for c in [cfg.get("id"), cfg.get("nombre"), cfg.get("telefono"), cfg.get("direccion"), cfg.get("creado")] if c]
    q = text(f"SELECT {', '.join(cols)} FROM {tbl} ORDER BY {cfg.get('nombre')}")
    return pd.read_sql(q, get_mysql_engine())

@st.cache_data(ttl=300)
def df_formularios(cliente_id: int | None = None, tipo: str | None = None,
                   desde: datetime | None = None, hasta: datetime | None = None) -> pd.DataFrame:
    cfg = CONFIG_SCHEMA["formularios"]
    tbl = cfg["table"]
    where = ["1=1"]
    params: Dict[str, Any] = {}
    if cliente_id is not None:
        where.append(f"{cfg['cliente_id']} = :cid"); params["cid"] = cliente_id
    if tipo:
        where.append(f"{cfg['tipo']} = :tipo"); params["tipo"] = tipo
    if desde:
        where.append(f"{cfg['fecha']} >= :desde"); params["desde"] = desde
    if hasta:
        where.append(f"{cfg['fecha']} <= :hasta"); params["hasta"] = hasta
    cols = [c for c in [cfg.get("id"), cfg.get("cliente_id"), cfg.get("tipo"), cfg.get("fecha"), cfg.get("payload")] if c]
    q = text(f"SELECT {', '.join(cols)} FROM {tbl} WHERE {' AND '.join(where)} ORDER BY {cfg['fecha']} DESC")
    return pd.read_sql(q, get_mysql_engine(), params=params)

@st.cache_data(ttl=300)
def df_eventos(nombre: str, cliente_id: int | None = None,
               desde: datetime | None = None, hasta: datetime | None = None) -> pd.DataFrame:
    cfg = CONFIG_SCHEMA[nombre]
    tbl = cfg["table"]
    where = ["1=1"]
    params: Dict[str, Any] = {}
    if cliente_id is not None and cfg.get("cliente_id"):
        where.append(f"{cfg['cliente_id']} = :cid"); params["cid"] = cliente_id
    if desde:
        where.append(f"{cfg['fecha']} >= :desde"); params["desde"] = desde
    if hasta:
        where.append(f"{cfg['fecha']} <= :hasta"); params["hasta"] = hasta
    cols = [c for c in [cfg.get("id"), cfg.get("cliente_id"), cfg.get("fecha"), cfg.get("texto"),
                        cfg.get("usuario_id"), cfg.get("estado"), cfg.get("valor")] if c]
    order_col = cfg.get("fecha") or cfg.get("id")
    q = text(f"SELECT {', '.join(cols)} FROM {tbl} WHERE {' AND '.join(where)} ORDER BY {order_col} DESC")
    return pd.read_sql(q, get_mysql_engine(), params=params)

# ----------------------------
# UI – Sidebar
# ----------------------------
st.title("📊 Dashboard SQL — Make + Forms")

with st.sidebar:
    st.header("Filtros")
    clientes = df_clientes()
    if clientes.empty:
        st.error("No hay clientes. Revisa la conexión y el mapeo de columnas en CONFIG_SCHEMA.")
        st.stop()

    id_col = CONFIG_SCHEMA["clientes"]["id"]
    name_col = CONFIG_SCHEMA["clientes"]["nombre"]
    opciones = ["(Todos)"] + [f"#{int(row[id_col])} – {row[name_col]}" for _, row in clientes.iterrows()]
    sel_cliente = st.selectbox("Cliente", opciones)
    cliente_id = None if sel_cliente == "(Todos)" else int(sel_cliente.split("–")[0].replace("#", "").strip())

    hoy = datetime.utcnow().date()
    desde_d = st.date_input("Desde", hoy - timedelta(days=30))
    hasta_d = st.date_input("Hasta", hoy)

    fcfg = CONFIG_SCHEMA["formularios"]
    f_all = df_formularios()
    if not f_all.empty and fcfg["tipo"] in f_all.columns:
        tipos = sorted(pd.Series(f_all[fcfg["tipo"]]).dropna().unique().tolist())
    else:
        tipos = []
    tipo_sel = st.selectbox("Tipo de formulario", ["(Todos)"] + tipos)
    tipo_form = None if tipo_sel == "(Todos)" else tipo_sel

# ----------------------------
# Tabs principales
# ----------------------------
T1, T2, T3, T4 = st.tabs(["Resumen", "Formularios", "Diagnósticos", "Comentarios"])

desde_dt = datetime.combine(desde_d, datetime.min.time())
hasta_dt = datetime.combine(hasta_d, datetime.max.time())

with T1:
    col1, col2, col3 = st.columns(3)

    forms = df_formularios(cliente_id, tipo_form, desde_dt, hasta_dt)
    diags = df_eventos("diagnosticos", cliente_id, desde_dt, hasta_dt)
    comms = df_eventos("comentarios", cliente_id, desde_dt, hasta_dt)

    col1.metric("Formularios", len(forms))
    col2.metric("Diagnósticos", len(diags))
    col3.metric("Comentarios", len(comms))

    st.markdown("---")
    st.subheader("Últimos eventos")
    cA, cB = st.columns(2)
    with cA:
        st.caption("Diagnósticos recientes")
        st.dataframe(diags.head(20), use_container_width=True)
    with cB:
        st.caption("Comentarios recientes")
        st.dataframe(comms.head(20), use_container_width=True)

with T2:
    st.subheader("Formularios")
    if forms.empty:
        st.info("Sin formularios en el rango/cliente seleccionado.")
    else:
        st.dataframe(forms, use_container_width=True)
        cfgf = CONFIG_SCHEMA["formularios"]
        if cfgf.get("payload") and cfgf["payload"] in forms.columns:
            st.markdown("### Detalle de un envío")
            idx = st.number_input("Fila (índice)", min_value=0, max_value=len(forms)-1, value=0, step=1)
            registro = forms.iloc[int(idx)].to_dict()
            st.json(registro.get(cfgf["payload"], {}))
        st.download_button("📥 CSV", data=forms.to_csv(index=False).encode("utf-8"), file_name="formularios.csv")

with T3:
    st.subheader("Diagnósticos")
    if diags.empty:
        st.info("Sin diagnósticos en el rango/cliente seleccionado.")
    else:
        st.dataframe(diags, use_container_width=True)
        st.download_button("📥 CSV", data=diags.to_csv(index=False).encode("utf-8"), file_name="diagnosticos.csv")

with T4:
    st.subheader("Comentarios")
    if comms.empty:
        st.info("Sin comentarios en el rango/cliente seleccionado.")
    else:
        st.dataframe(comms, use_container_width=True)
        st.download_button("📥 CSV", data=comms.to_csv(index=False).encode("utf-8"), file_name="comentarios.csv")

st.caption("© Dashboard SQL (Make + Forms) — Ajusta CONFIG_SCHEMA para calzar con tus tablas reales.")